---
rules:
    import/no-unresolved: 2
    import/named: 2
    # import/default: 2
    import/namespace: 2
    import/export: 2

    import/no-named-as-default: 1
    # import/no-named-as-default-member: 1
    import/no-duplicates: 1
    import/first: 1
    import/order:
        - 1
        - groups:
              - builtin
              - external
              - internal
              - unknown
              - parent
              - sibling
              - index
          newlines-between: never
    import/no-useless-path-segments: 2
    import/no-self-import: 2
    import/no-absolute-path: 2
    import/no-commonjs: 2
    import/no-amd: 2
    import/no-extraneous-dependencies:
        - 2
        - devDependencies: true
          peerDependencies: false
          optionalDependencies: false

    import/exports-last: 1
    import/group-exports: 1
    # import/no-default-export: 2
    import/no-mutable-exports: 2
    import/no-named-default: 2
