printWidth: 100
tabWidth: 4
useTabs: false
semi: false
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: avoid
endOfLine: lf

overrides:
  - files: '*.yml'
    options:
      tabWidth: 2
