// pixi imports have side-effects due to the extensions system
import '@pixi/mixin-cache-as-bitmap'
// import '@pixi/mixin-get-child-by-name'
// import '@pixi/mixin-get-global-position'
// import '@pixi/accessibility'
import '@pixi/app'
import '@pixi/assets'
import '@pixi/compressed-textures'
import '@pixi/core'
import '@pixi/display'
import '@pixi/events'
import '@pixi/extract'
import '@pixi/filter-alpha'
// import '@pixi/filter-blur'
// import '@pixi/filter-color-matrix'
// import '@pixi/filter-displacement'
// import '@pixi/filter-fxaa'
// import '@pixi/filter-noise'
import '@pixi/graphics'
// import '@pixi/mesh'
// import '@pixi/mesh-extras'
// import '@pixi/particle-container'
// import '@pixi/prepare'
import '@pixi/sprite'
// import '@pixi/sprite-animated'
import '@pixi/sprite-tiling'
// import '@pixi/spritesheet'
import '@pixi/text'
// import '@pixi/text-bitmap'
// import '@pixi/text-html'
